services:
  - type: web
    name: frontend-sgad
    env: static
    buildCommand: cd codexa-frontend && npm install && npm run build
    publishPath: codexa-frontend/dist

  - type: pserv
    name: api-gateway-sgad
    env: docker
    dockerfilePath: ./Dockerfile

  - type: pserv
    name: merged-backend-sgad
    env: docker
    dockerfilePath: ./Dockerfile
