services:
  - type: web
    name: frontend-sgad
    runtime: node
    rootDir: codexa-frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    plan: free

  - type: web
    name: config-server-sgad
    runtime: docker
    rootDir: config-service
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GIT_USERNAME
        sync: false
      - key: GIT_PASSWORD
        sync: false
      - key: EUREKA_CLIENT_ENABLED
        value: "false"
      - key: SPRING_CLOUD_DISCOVERY_ENABLED
        value: "false"
    plan: free

  - type: web
    name: backend-sgad
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mental-health-db
          property: connectionString
      - key: CONFIG_SERVER_URL
        value: "https://config-server-sgad.onrender.com"
      - key: SPRING_CLOUD_CONFIG_ENABLED
        value: "true"
      - key: SPRING_CLOUD_CONFIG_URI
        value: "https://config-server-sgad.onrender.com"
      - key: SPRING_CLOUD_CONFIG_FAIL_FAST
        value: "false"
      - key: SPRING_CLOUD_DISCOVERY_ENABLED
        value: "false"
      - key: EUREKA_CLIENT_ENABLED
        value: "false"
    plan: free
