databases:
  - name: codexa-postgres
    databaseName: codexa

services:
  - type: web
    name: codexa-frontend
    env: static
    buildCommand: cd codexa-frontend && npm install && npm run build

  - type: pserv
    name: codexa-api-gateway
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      SERVICE_NAME: api-gateway

  - type: pserv
    name: codexa-account-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      SERVICE_NAME: account-service
      DATABASE_URL: ${codexa-postgres.DATABASE_URL}

  - type: pserv
    name: codexa-intelligence-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      SERVICE_NAME: intelligence-service
      DATABASE_URL: ${codexa-postgres.DATABASE_URL}
