apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codexa-cert
  namespace: codexa-ai
spec:
  secretName: codexa-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${CODEXA_APP_HOST}
    - ${CODEXA_API_HOST}